server.port: 8081

client.locale: en

i18n:
  params:
    baseName: i18n_
    extension: properties
    locales:
      - ru
      - en

domain:
  change.notifier.queue.capacity: 1_000
  monitoring.destination.tag:
    creation: /topic/tagCreationResponse/
    updating: /topic/tagUpdatingResponse/
    deleting: /topic/tagDeletingResponse/
