export const SUBSCRIPTION = {
	CLIENT_PARAMS: 'SUBSCRIPTION_CLIENT_PARAMS',
	I18N: 'SUBSCRIPTION_I18N',
	AUTH_REQUEST: 'SUBSCRIPTION_AUTH_REQUEST',
	LOGOUT_REQUEST: 'SUBSCRIPTION_LOGOUT_REQUEST',
	TAG: {
		LOADINTG: 'SUBSCRIPTION_TAG_LOADING',
		CREATION: 'SUBSCRIPTION_TAG_CREATION',
		UPDATING: 'SUBSCRIPTION_TAG_UPDATING',
		REMOVING: 'SUBSCRIPTION_TAG_REMOVING'
	}
};
