export const TAG = {
	REQUEST: {
		LOAD  : 'TAG_REQUEST_LOAD',
		CREATE: 'TAG_REQUEST_CREATE',
		UPDATE: 'TAG_REQUEST_UPDATE',
		REMOVE: 'TAG_REQUEST_REMOVE'
	},
	RESPONSE: {
		LOAD  : 'TAG_RESPONSE_LOAD',
		CREATE: 'TAG_RESPONSE_CREATE',
		UPDATE: 'TAG_RESPONSE_UPDATE',
		REMOVE: 'TAG_RESPONSE_REMOVE'
	},
	STORAGE: {
		CLEAR: 'TAG_STORAGE_CLEAR'
	}
};
